import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import FullScreenLoader from '@/components/FullScreenLoader'
import LeftSidebar from '@/components/LeftSidebar'
import RightSidebar from '@/components/RightSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} overflow-hidden grid `} style={{gridTemplateColumns:'80px auto 80px'}}>
					<FullScreenLoader />
					<LeftSidebar className='' />
				{children}
					<RightSidebar className='bg-blue-300' />
			</body>
		</html>
	)
}

// TODO maybe make the layout grid and fix the sidebars left and ight and they can grow and shrink