import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import FullScreenLoader from '@/components/full-screen-loader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-white`}>
					<FullScreenLoader />
				{children}
			</body>
		</html>
	)
}
